apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: volume-pod
  volumes:
    - name: volume-pod
      hostPath:
        path: /home/volume
        type: DirectoryOrCreate
